import {
  HomeHero,
  WhatWeDo,
  TestimonialsSection,
  BlogSection,
  HowItWorks,
  Presentation,
  Features,
  Cta,
  SpecialFeatures,
  Quote,
  WelcomeSteps,
  VideoSection,
  FormSection,
  TeamSection,
  SimpleHero,
  FeaturesTabs,
  ToolsCards,
  PricingSection,
  // DiscoverListing
} from 'apical-components'

import DiscoverListing from './components/DiscoverListing'

export default {
  HomeHero,
  WhatWeDo,
  TestimonialsSection,
  BlogSection,
  HowItWorks,
  // SectionContainer,
  Presentation,
  FeaturesSection: Features,
  // OnboardingForm,
  FormSection,
  Cta,
  SpecialFeatures,
  Quote,
  WelcomeSteps,
  VideoSection,
  TeamSection,
  // RestartingTypist,
  SimpleHero,
  FeaturesTabs,
  ToolsCards,
  PricingSection,
  DiscoverListing,
}
